version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./vqa-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
